[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
somnia_testnet = "https://dream-rpc.somnia.network"
somnia_mainnet = "https://api.infra.mainnet.somnia.network/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options